# Site settings
title: OPUS
email: opus.uofm@umanitoba.ca
address:
  building: "206 Allen Building"
  university: "University of Manitoba"
url: https://gharveymn.github.io/opusweb/
description: "The Organization of Physics Undergraduate Students (OPUS) is a student-run group at the University of Manitoba. We provide tutoring services, volunteer opportunities, events, and more for physics undergraduate students!"
baseurl: "/web"

destination: ../build

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: OPUS

# Social networks (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/opus_uofm/

# Build settings
markdown: kramdown
permalink: pretty
plugins:
- jekyll-seo-tag
